"""occasion tone

Revision ID: 48d88a276e9c
Revises: a678467d384d
Create Date: 2024-08-04 09:45:01.514460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d88a276e9c'
down_revision: Union[str, None] = 'a678467d384d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occasions', sa.Column('tone', sa.String(), nullable=True))
    op.drop_index('ix_occasions_custom_input', table_name='occasions')
    op.drop_index('ix_occasions_date', table_name='occasions')
    op.drop_index('ix_occasions_email', table_name='occasions')
    op.drop_index('ix_occasions_label', table_name='occasions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_occasions_label', 'occasions', ['label'], unique=False)
    op.create_index('ix_occasions_email', 'occasions', ['email'], unique=False)
    op.create_index('ix_occasions_date', 'occasions', ['date'], unique=False)
    op.create_index('ix_occasions_custom_input', 'occasions', ['custom_input'], unique=False)
    op.drop_column('occasions', 'tone')
    # ### end Alembic commands ###
