"""Add is_recurring field to Occasion model

Revision ID: ad1cc4756bfd
Revises: 83d49ad2766f
Create Date: 2024-10-14 10:07:16.636068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1cc4756bfd'
down_revision: Union[str, None] = '83d49ad2766f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occasions', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occasions', 'is_recurring')
    # ### end Alembic commands ###
