"""initial migration

Revision ID: b27755667b3a
Revises: 
Create Date: 2024-06-19 16:57:02.013998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27755667b3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created'), 'users', ['created'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('occasions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('custom_input', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('date_processed', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occasions_custom_input'), 'occasions', ['custom_input'], unique=False)
    op.create_index(op.f('ix_occasions_date'), 'occasions', ['date'], unique=False)
    op.create_index(op.f('ix_occasions_email'), 'occasions', ['email'], unique=False)
    op.create_index(op.f('ix_occasions_id'), 'occasions', ['id'], unique=False)
    op.create_index(op.f('ix_occasions_type'), 'occasions', ['type'], unique=False)
    op.create_index(op.f('ix_occasions_user_id'), 'occasions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occasions_user_id'), table_name='occasions')
    op.drop_index(op.f('ix_occasions_type'), table_name='occasions')
    op.drop_index(op.f('ix_occasions_id'), table_name='occasions')
    op.drop_index(op.f('ix_occasions_email'), table_name='occasions')
    op.drop_index(op.f('ix_occasions_date'), table_name='occasions')
    op.drop_index(op.f('ix_occasions_custom_input'), table_name='occasions')
    op.drop_table('occasions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
