"""rename email_verified to is_email_verified

Revision ID: d220e3ae9421
Revises: c1261040f817
Create Date: 2024-09-29 19:20:59.135622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd220e3ae9421'
down_revision: Union[str, None] = 'c1261040f817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
