"""Add is_draft field to Occasion model

Revision ID: d5497d27cfa8
Revises: ad1cc4756bfd
Create Date: 2024-10-14 10:40:37.171426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5497d27cfa8'
down_revision: Union[str, None] = 'ad1cc4756bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occasions', sa.Column('is_draft', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occasions', 'is_draft')
    # ### end Alembic commands ###
