"""occasion tone field

Revision ID: e4d9283517ef
Revises: a678467d384d
Create Date: 2024-08-04 09:19:54.363920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d9283517ef'
down_revision: Union[str, None] = 'a678467d384d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occasions', sa.Column('tone', sa.Enum('NORMAL', 'SYMPATHETIC', 'ENCOURAGING', 'CELEBRATORY', 'SARCASTIC', name='occasiontone'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occasions', 'tone')
    # ### end Alembic commands ###
